# This uses variable expansion so you can select machine(s) from the command line
# using the -e flag.  See README for instructions on how to use.
- hosts: ~tag_Name_{{ machine }}_stage
  pre_tasks:
  - fail: msg="This playbook only runnable on 'app' machines"
    when: "'app' not in machine"
  sudo: True
  vars:
    not_prod: true
    secure_dir: "../../../edx-secret/ansible"
    local_dir: "{{secure_dir}}/local"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_stage_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_stage_users.yml"
    - "{{ secure_dir }}/vars/shib_stage_vars.yml"
    #- "{{ secure_dir }}/vars/datadog_stage.yml"
  roles:
    - common
    - supervisor
    - role: user
      USER_INFO:
        - name: sefk
          github: true
          type: admin
        - name: jbau
          github: true
          type: admin
        - name: jrbl
          github: true
          type: admin
        - name: ali123
          github: true
          type: admin
        - name: caesar2164
          github: true
          type: admin
        - name: dcadams
          github: true
          type: admin
        - name: nparlante
          github: true
          type: admin
        - name: stvstnfrd
          github: true
          type: admin
        - name: jinpa
          github: true
        - name: gbruhns
          github: true
        - name: paepcke
          github: true
        - name: akshayka
          github: true
        - name: halawa
          github: true
        - name: amayalah
          github: true
        - name: mondiaz
          github: true
      tags: users
    - role: nginx
      nginx_sites:
        - lms
        - cms
        - verify
      nginx_template_directory: "{{local_dir}}/nginx/templates/"
      nginx_default_sites:
        - lms
    - role: edxapp
      devstack: false
    - apache
    - shibboleth
    #- datadog
    #- splunkforwarder

