---
- name: Basic util setup on all hosts
  # This uses variable expansion so you can select machine(s) from the command line
  # using the -e flag.  See README for instructions on how to use.
  hosts: ~tag_Name_{{machine}}_stage
  pre_tasks:
  - fail: msg="This playbook only runnable on 'util' machines"
    when: "'util' not in machine"
  sudo: True
  gather_facts: True
  vars:
    secure_dir: ../../../edx-secret/ansible
    local_dir: "{{secure_dir}}/local"
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_stage_vars.yml"
    - "{{ secure_dir }}/vars/xqueue_stage_vars.yml"
    - "{{ secure_dir }}/vars/edxapp_stage_users.yml"
    - "{{ secure_dir }}/vars/datadog_stage.yml"
  roles:
    - role: common
    - role: supervisor
    - role: user
      tags: users
    - role: edxapp
      celery_worker: True
      devstack: false
    - role: nginx
      nginx_sites:
      - xqueue
      - basic-auth
      tags: nginx
    - role: xqueue
      xqueue_create_db: "no"
      xqueue_create_users: false
      tags: xqueue

#- name: deploy certs to first util machine only
#  hosts: ~tag_Name_util1_stage
#  sudo: True
#  gather_facts: True
#  vars:
#    secure_dir: "../../../configuration-secure/ansible"
#    local_dir: "{{secure_dir}}/local"
#    migrate_db: "no"
#  vars_files:
#    - "roles/common/defaults/main.yml"
#    - "roles/supervisor/defaults/main.yml"
#    - "{{ secure_dir }}/vars/edxapp_stage_vars.yml"
#    - "{{ secure_dir }}/vars/certs_stage_vars.yml"
#  roles:
#    - role: certs
#      tags: certs

- name: run the notifier on the first util machine only
  hosts: ~tag_Name_util1_stage
  sudo: True
  vars:
    secure_dir: "../../../configuration-secure/ansible"
    local_dir: "{{secure_dir}}/local"
    migrate_db: "no"
  vars_files:
    - "roles/common/defaults/main.yml"
    - "roles/supervisor/defaults/main.yml"
    - "{{ secure_dir }}/vars/notifier_stage_vars.yml"
  roles:
    - role: notifier
      tags: notifier
